version: '3.8'
services:
  db2:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=kufarAnalog
      - MYSQL_ROOT_PASSWORD=02022001
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql2
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local